// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1FvEanZcw-3f6KKR9niZkGUeXT4XpANM',
    appId: '1:1032388408133:android:6bf8ac8515fbd91d07042c',
    messagingSenderId: '1032388408133',
    projectId: 'radiant-toe',
    storageBucket: 'radiant-toe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYMCqk9HOAjWv3z_iPPHUTf8saDJmFJ-8',
    appId: '1:1032388408133:ios:dd8e0987581f235707042c',
    messagingSenderId: '1032388408133',
    projectId: 'radiant-toe',
    storageBucket: 'radiant-toe.firebasestorage.app',
    iosBundleId: 'com.example.tictactoeP002',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1FvEanZcw-3f6KKR9niZkGUeXT4XpANM',
    appId: '1:1032388408133:web:6bf8ac8515fbd91d07042c',
    messagingSenderId: '1032388408133',
    projectId: 'radiant-toe',
    authDomain: 'radiant-toe.firebaseapp.com',
    storageBucket: 'radiant-toe.firebasestorage.app',
  );
}
